### ISSUE TITLE
Snap : joystick

### ISSUE THREAD

**Issue by benyanke** [diddlesnaps/supertuxkart#2]
It would be great to be able to use a plug like joystick.

I saw another similar snap that you could run a command like:
```
snap connect supertuxkart:process-control :process-control
snap connect supertuxkart:joystick :joystick
```

Perhaps this could even be done by default, if that's an option.

Any chance this could come here?

**Comment by lucyllewy** [comment]
This is already possible. On any system run:

```bash
sudo snap connect supertuxkart:joystick
```
or on Ubuntu you can use the Software Centre to do it via a GUI:

![peek 2018-12-18 12-39](https://user-images.githubusercontent.com/147548/50154847-7452b880-02c2-11e9-90d2-26a4125ed0bf.gif)

**Comment by lucyllewy** [comment]
This issue hasn't had any replies for some time, so I'm going to close it for now. Please reopen if it is still a problem, or open a new issue for other problems.

**Comment by ozdreamern** [comment]
I'd like to reopen this, or open a new issue specifically about Wiimotes (or maybe Bluetooth gamepads in general).  I've tried to configure STK to [use a Wiimote](https://supertuxkart.net/Wiimote) without success: none of mine ever successfully pair, and my guess is this fails because the snap doesn't have permission to access bluetooth devices.

STK handles this controller type via the wiiuse library, which in turn depends on kernel bluetooth support and the BlueZ drivers (both are enabled on my Ubuntu 18.04 system, I use several BT devices).  When STK is run with logging enabled, this is what I see:
> wiiuse v0.15.4 loaded.
>  De-facto official fork at http://github.com/wiiuse/wiiuse
>  Original By: Michael Laforest <thepara[at]gmail{dot}com> <https://sourceforge.net/projects/wiiuse/>
> [INFO] wiiuse clean up...
> hci_get_route: Permission denied

I wonder if this could be resolved by plugging into the [bluetooth-control](https://docs.snapcraft.io/bluetooth-control-interface) and/or [bluez](https://docs.snapcraft.io/t/the-bluez-interface/7772) interfaces?
